---
- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - build-essential
      - libtagc0
      - zlib1g

- name: Make videotag user
  user:
    name: videotag
    shell: /bin/nologin
    home: /opt/ipfs-video-tags

- name: Copy binary
  copy:
    src: ipfs-video-tags-exe
    dest: /opt/ipfs-video-tags
    mode: u=rwx,g=rx,o=rx

- name: Copy systemctl
  copy:
    src: videotag.service
    dest: /etc/systemd/system
  notify: enable videotag service
